# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            disekt
tagline:          'CTF Team'
description:      'disekt'
url:              http://disekt.org

author:
  name:           'disekt'
  url:            https://twitter.com/disekt

paginate:         25

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/disekt

blog:             http://blog.disekt.org
